#ifndef P4MLIR_DIALECT_P4HIR_P4HIR_OPINTERFACES_H
#define P4MLIR_DIALECT_P4HIR_P4HIR_OPINTERFACES_H

#include "mlir/IR/OpDefinition.h"

#include "p4mlir/Dialect/P4HIR/P4HIR_OpInterfaces.h.inc"

#endif  // P4MLIR_DIALECT_P4HIR_P4HIR_OPINTERFACES_H
