// SPDX-FileCopyrightText: 2025 The P4 Language Consortium
//
// SPDX-License-Identifier: Apache-2.0

#ifndef P4MLIR_DIALECT_P4CORELIB_P4CORELIB_TD
#define P4MLIR_DIALECT_P4CORELIB_P4CORELIB_TD

include "p4mlir/Dialect/P4CoreLib/P4CoreLib_Dialect.td"
include "p4mlir/Dialect/P4CoreLib/P4CoreLib_Ops.td"
include "p4mlir/Dialect/P4CoreLib/P4CoreLib_Types.td"

#endif // P4MLIR_DIALECT_P4CORELIB_P4CORELIB_TD
