// SPDX-FileCopyrightText: 2025 The P4 Language Consortium
//
// SPDX-License-Identifier: Apache-2.0

// RUN: p4mlir-opt -p4hir-copyin-copyout-elimination < %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

!b10i = !p4hir.bit<10>
!i16i = !p4hir.int<16>
!validity_bit = !p4hir.validity.bit
#InnerPipe_flag = #p4hir.ctor_param<@InnerPipe, "flag"> : !p4hir.bool
#false = #p4hir.bool<false> : !p4hir.bool
#true = #p4hir.bool<true> : !p4hir.bool
!MyHeader = !p4hir.header<"MyHeader", f1: !i16i, __valid: !validity_bit>
#Pipe_ctr_arg1 = #p4hir.ctor_param<@Pipe, "ctr_arg1"> : !i16i
#int1_b10i = #p4hir.int<1> : !b10i
#Pipe_hdr_arg = #p4hir.ctor_param<@Pipe, "hdr_arg"> : !MyHeader
module {

  p4hir.control @InnerPipe(%arg0: !b10i {p4hir.dir = #p4hir<dir undir>, p4hir.param_name = "arg1"}, %arg1: !i16i {p4hir.dir = #p4hir<dir in>, p4hir.param_name = "arg2"}, %arg2: !p4hir.ref<!i16i> {p4hir.dir = #p4hir<dir out>, p4hir.param_name = "arg3"})(flag: !p4hir.bool) {
    %flag = p4hir.const ["flag"] #InnerPipe_flag
    p4hir.control_local @__local_InnerPipe_arg1_0 = %arg0 : !b10i
    p4hir.control_local @__local_InnerPipe_arg2_0 = %arg1 : !i16i
    p4hir.control_local @__local_InnerPipe_arg3_0 = %arg2 : !p4hir.ref<!i16i>
    p4hir.control_apply {
    }
  }

// Check dealiasing of control applies  
// CHECK-LABEL:   p4hir.control @Pipe(
// CHECK-SAME:      %[[ARG0:.*]]: !b10i {p4hir.dir = #p4hir<dir undir>, p4hir.param_name = "arg1"},
// CHECK-SAME:      %[[ARG1:.*]]: !i16i {p4hir.dir = #p4hir<dir in>, p4hir.param_name = "arg2"},
// CHECK-SAME:      %[[ARG2:.*]]: !p4hir.ref<!i16i> {p4hir.dir = #p4hir<dir out>, p4hir.param_name = "arg3"},
// CHECK-SAME:      %[[ARG3:.*]]: !p4hir.ref<!i16i> {p4hir.dir = #p4hir<dir inout>, p4hir.param_name = "arg4"})(ctr_arg1: !i16i, hdr_arg: !MyHeader) {
// CHECK:           p4hir.control_local @__local_Pipe_arg1_0 = %[[ARG0]] : !b10i
// CHECK:           p4hir.control_local @__local_Pipe_arg2_0 = %[[ARG1]] : !i16i
// CHECK:           p4hir.control_local @__local_Pipe_arg3_0 = %[[ARG2]] : !p4hir.ref<!i16i>
// CHECK:           p4hir.control_local @__local_Pipe_arg4_0 = %[[ARG3]] : !p4hir.ref<!i16i>
// CHECK:           p4hir.instantiate @InnerPipe (%{{.*}} : !p4hir.bool) as @inner1
// CHECK:           p4hir.instantiate @InnerPipe (%{{.*}} : !p4hir.bool) as @inner2
// CHECK:           p4hir.control_apply {
// CHECK:             p4hir.call @Pipe::@bar () : () -> ()
// CHECK:             %[[VAL_7:.*]] = p4hir.variable ["x1"] : <!i16i>
// CHECK:             p4hir.scope {
// CHECK:               p4hir.apply @inner1(%{{.*}}, %{{.*}}, %[[VAL_7]]) : (!b10i, !i16i, !p4hir.ref<!i16i>) -> ()
// CHECK:             }
// CHECK:           }
// CHECK:         }
  p4hir.control @Pipe(%arg0: !b10i {p4hir.dir = #p4hir<dir undir>, p4hir.param_name = "arg1"}, %arg1: !i16i {p4hir.dir = #p4hir<dir in>, p4hir.param_name = "arg2"}, %arg2: !p4hir.ref<!i16i> {p4hir.dir = #p4hir<dir out>, p4hir.param_name = "arg3"}, %arg3: !p4hir.ref<!i16i> {p4hir.dir = #p4hir<dir inout>, p4hir.param_name = "arg4"})(ctr_arg1: !i16i, hdr_arg: !MyHeader) {
    %ctr_arg1 = p4hir.const ["ctr_arg1"] #Pipe_ctr_arg1
    %hdr_arg = p4hir.const ["hdr_arg"] #Pipe_hdr_arg
    p4hir.control_local @__local_Pipe_arg1_0 = %arg0 : !b10i
    p4hir.control_local @__local_Pipe_arg2_0 = %arg1 : !i16i
    p4hir.control_local @__local_Pipe_arg3_0 = %arg2 : !p4hir.ref<!i16i>
    p4hir.control_local @__local_Pipe_arg4_0 = %arg3 : !p4hir.ref<!i16i>
    %true = p4hir.const #true
    p4hir.instantiate @InnerPipe (%true : !p4hir.bool) as @inner1
    %false = p4hir.const #false
    p4hir.instantiate @InnerPipe (%false : !p4hir.bool) as @inner2
    p4hir.func action @bar() {
      %false_0 = p4hir.const #false
      %hasReturned = p4hir.variable ["hasReturned", init] : <!p4hir.bool>
      p4hir.assign %false_0, %hasReturned : <!p4hir.bool>
      %x1 = p4hir.variable ["x1"] : <!i16i>
      p4hir.scope {
        %true_1 = p4hir.const #true
        p4hir.assign %true_1, %hasReturned : <!p4hir.bool>
      }
      p4hir.return
    }
    p4hir.control_apply {
      p4hir.call @Pipe::@bar () : () -> ()
      %x1 = p4hir.variable ["x1"] : <!i16i>
      p4hir.scope {
        %c1_b10i = p4hir.const #int1_b10i
        %arg3_out_arg = p4hir.variable ["arg3_out_arg"] : <!i16i>
        p4hir.apply @inner1(%c1_b10i, %ctr_arg1, %arg3_out_arg) : (!b10i, !i16i, !p4hir.ref<!i16i>) -> ()
        %val = p4hir.read %arg3_out_arg : <!i16i>
        p4hir.assign %val, %x1 : <!i16i>
      }
    }
  }
}
