// RUN: p4mlir-opt -p4hir-copyin-copyout-elimination < %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK: #[[$INOUT:.+]] = #p4hir<dir inout>
// CHECK: #[[$INT1:.+]] = #p4hir.int<1> : !b1i
!b1i = !p4hir.bit<1>
!b8i = !p4hir.bit<8>
#inout = #p4hir<dir inout>
#int1_b1i = #p4hir.int<1> : !b1i
module {
  p4hir.func @g(!p4hir.ref<!b1i> {p4hir.dir = #inout, p4hir.param_name = "z"}) -> !b1i
// CHECK-LABEL:   p4hir.func action @test1() {
// CHECK:           %[[VAL_0:.*]] = p4hir.const #[[$INT1]]
// CHECK:           %[[VAL_1:.*]] = p4hir.variable ["a"] : <!b1i>
// CHECK:           p4hir.scope {
// CHECK:             p4hir.assign %[[VAL_0]], %[[VAL_1]] : <!b1i>
// CHECK:           }
// CHECK:           p4hir.return
// CHECK:         }
  p4hir.func action @test1() {
    %a = p4hir.variable ["a"] : <!b1i>
    p4hir.scope {
      %c1_b1i = p4hir.const #int1_b1i
      %zz_out_arg = p4hir.variable ["zz_out_arg"] : <!b1i>
      p4hir.assign %c1_b1i, %zz_out_arg : <!b1i>
      %val = p4hir.read %zz_out_arg : <!b1i>
      p4hir.assign %val, %a : <!b1i>
    }
    p4hir.return
  }
// CHECK-LABEL:   p4hir.func action @test2() {
// CHECK:           %[[VAL_0:.*]] = p4hir.const #[[$INT1]]
// CHECK:           %[[VAL_1:.*]] = p4hir.variable ["a"] : <!b1i>
// CHECK:           p4hir.scope {
// CHECK:             p4hir.assign %[[VAL_0]], %[[VAL_1]] : <!b1i>
// CHECK:           }
// CHECK:           p4hir.return
// CHECK:         }
  p4hir.func action @test2() {
    %a = p4hir.variable ["a"] : <!b1i>
    p4hir.scope {
      %c1_b1i = p4hir.const #int1_b1i
      %z_inout_arg = p4hir.variable ["z_inout_arg", init] : <!b1i>
      %val = p4hir.read %a : <!b1i>
      p4hir.assign %val, %z_inout_arg : <!b1i>
      p4hir.assign %c1_b1i, %z_inout_arg : <!b1i>
      %val_0 = p4hir.read %z_inout_arg : <!b1i>
      p4hir.assign %val_0, %a : <!b1i>
    }
    p4hir.return
  }
// CHECK-LABEL:   p4hir.func action @test3() {
// CHECK:           %[[VAL_0:.*]] = p4hir.const #[[$INT1]]
// CHECK:           %[[VAL_1:.*]] = p4hir.variable ["a"] : <!b1i>
// CHECK:           p4hir.scope {
// CHECK:             %[[VAL_2:.*]] = p4hir.variable ["x_inout_arg", init] : <!b1i>
// CHECK:             %[[VAL_3:.*]] = p4hir.read %[[VAL_1]] : <!b1i>
// CHECK:             p4hir.assign %[[VAL_3]], %[[VAL_2]] : <!b1i>
// CHECK:             %[[VAL_4:.*]] = p4hir.scope {
// CHECK:               %[[VAL_5:.*]] = p4hir.call @g (%[[VAL_1]]) : (!p4hir.ref<!b1i>) -> !b1i
// CHECK:               p4hir.yield %[[VAL_5]] : !b1i
// CHECK:             } : !b1i
// CHECK:             p4hir.assign %[[VAL_0]], %[[VAL_2]] : <!b1i>
// CHECK:             %[[VAL_6:.*]] = p4hir.read %[[VAL_2]] : <!b1i>
// CHECK:             p4hir.assign %[[VAL_6]], %[[VAL_1]] : <!b1i>
// CHECK:           }
// CHECK:           p4hir.return
// CHECK:         }
  p4hir.func action @test3() {
    %a = p4hir.variable ["a"] : <!b1i>
    p4hir.scope {
      %x_inout_arg = p4hir.variable ["x_inout_arg", init] : <!b1i>
      %val = p4hir.read %a : <!b1i>
      p4hir.assign %val, %x_inout_arg : <!b1i>
      %0 = p4hir.scope {
        %z_inout_arg = p4hir.variable ["z_inout_arg", init] : <!b1i>
        %val_1 = p4hir.read %a : <!b1i>
        p4hir.assign %val_1, %z_inout_arg : <!b1i>
        %call = p4hir.call @g (%z_inout_arg) : (!p4hir.ref<!b1i>) -> !b1i
        %val_2 = p4hir.read %z_inout_arg : <!b1i>
        p4hir.assign %val_2, %a : <!b1i>
        p4hir.yield %call : !b1i
      } : !b1i
      %c1_b1i = p4hir.const #int1_b1i
      p4hir.assign %c1_b1i, %x_inout_arg : <!b1i>
      %val_0 = p4hir.read %x_inout_arg : <!b1i>
      p4hir.assign %val_0, %a : <!b1i>
    }
    p4hir.return
  }
// CHECK-LABEL:   p4hir.func action @test4(
// CHECK-SAME:      %[[ARG0:.*]]: !p4hir.ref<!b8i> {p4hir.dir = #[[$INOUT]], p4hir.param_name = "a"},
// CHECK-SAME:      %[[ARG1:.*]]: !p4hir.ref<!b8i> {p4hir.dir = #[[$INOUT]], p4hir.param_name = "b"}) {
// CHECK:           %[[VAL_0:.*]] = p4hir.read %[[ARG1]] : <!b8i>
// CHECK:           p4hir.assign %[[VAL_0]], %[[ARG0]] : <!b8i>
// CHECK:           p4hir.return
// CHECK:         }
  p4hir.func action @test4(%arg0: !p4hir.ref<!b8i> {p4hir.dir = #p4hir<dir inout>, p4hir.param_name = "a"}, %arg1: !p4hir.ref<!b8i> {p4hir.dir = #p4hir<dir inout>, p4hir.param_name = "b"}) {
    %c = p4hir.variable ["c", init] : <!b8i>
    %val = p4hir.read %arg0 : <!b8i>
    p4hir.assign %val, %c : <!b8i>
    %val_0 = p4hir.read %arg1 : <!b8i>
    p4hir.assign %val_0, %c : <!b8i>
    %val_1 = p4hir.read %c : <!b8i>
    p4hir.assign %val_1, %arg0 : <!b8i>
    p4hir.return
  }
// CHECK-LABEL:   p4hir.func action @test5(
// CHECK-SAME:      %[[ARG0:.*]]: !p4hir.ref<!b8i> {p4hir.dir = #[[$INOUT]], p4hir.param_name = "a"},
// CHECK-SAME:      %[[ARG1:.*]]: !p4hir.ref<!b8i> {p4hir.dir = #[[$INOUT]], p4hir.param_name = "b"},
// CHECK-SAME:      %[[ARG2:.*]]: !p4hir.bool {p4hir.dir = #p4hir<dir in>, p4hir.param_name = "cond"}) {
// CHECK:           %[[VAL_0:.*]] = p4hir.variable ["d"] : <!b8i>
// CHECK:           %[[VAL_1:.*]] = p4hir.read %[[ARG1]] : <!b8i>
// CHECK:           p4hir.assign %[[VAL_1]], %[[ARG0]] : <!b8i>
// CHECK:           p4hir.if %[[ARG2]] {
// CHECK:             %[[VAL_2:.*]] = p4hir.read %[[VAL_0]] : <!b8i>
// CHECK:             p4hir.assign %[[VAL_2]], %[[VAL_0]] : <!b8i>
// CHECK:           }
// CHECK:           p4hir.return
// CHECK:         }
  p4hir.func action @test5(%arg0: !p4hir.ref<!b8i> {p4hir.dir = #p4hir<dir inout>, p4hir.param_name = "a"}, %arg1: !p4hir.ref<!b8i> {p4hir.dir = #p4hir<dir inout>, p4hir.param_name = "b"},
                           %cond: !p4hir.bool {p4hir.dir = #p4hir<dir in>, p4hir.param_name = "cond"}) {
    %c = p4hir.variable ["c", init] : <!b8i>
    %d = p4hir.variable ["d"] : <!b8i>
    %val = p4hir.read %arg0 : <!b8i>
    p4hir.assign %val, %c : <!b8i>
    %val_0 = p4hir.read %arg1 : <!b8i>
    p4hir.assign %val_0, %c : <!b8i>
    p4hir.if %cond {
      %val_2 = p4hir.read %d : <!b8i>
      p4hir.assign %val_2, %d : <!b8i>
    }
    %val_1 = p4hir.read %c : <!b8i>
    p4hir.assign %val_1, %arg0 : <!b8i>
    p4hir.return
  }
// CHECK-LABEL:   p4hir.func action @test6(
// CHECK-SAME:      %[[ARG0:.*]]: !p4hir.ref<!b8i> {p4hir.dir = #[[$INOUT]], p4hir.param_name = "a"},
// CHECK-SAME:      %[[ARG1:.*]]: !p4hir.ref<!b8i> {p4hir.dir = #[[$INOUT]], p4hir.param_name = "b"},
// CHECK-SAME:      %[[ARG2:.*]]: !p4hir.bool {p4hir.dir = #p4hir<dir in>, p4hir.param_name = "cond"}) {
// CHECK:           %[[VAL_0:.*]] = p4hir.variable ["c", init] : <!b8i>
// CHECK:           %[[VAL_1:.*]] = p4hir.variable ["d"] : <!b8i>
// CHECK:           %[[VAL_2:.*]] = p4hir.read %[[ARG0]] : <!b8i>
// CHECK:           p4hir.assign %[[VAL_2]], %[[VAL_0]] : <!b8i>
// CHECK:           %[[VAL_3:.*]] = p4hir.read %[[ARG1]] : <!b8i>
// CHECK:           p4hir.assign %[[VAL_3]], %[[VAL_0]] : <!b8i>
// CHECK:           p4hir.if %[[ARG2]] {
// CHECK:             %[[VAL_4:.*]] = p4hir.read %[[VAL_0]] : <!b8i>
// CHECK:             p4hir.assign %[[VAL_4]], %[[VAL_1]] : <!b8i>
// CHECK:           }
// CHECK:           %[[VAL_5:.*]] = p4hir.read %[[VAL_0]] : <!b8i>
// CHECK:           p4hir.assign %[[VAL_5]], %[[ARG0]] : <!b8i>
// CHECK:           p4hir.return
// CHECK:         }
  p4hir.func action @test6(%arg0: !p4hir.ref<!b8i> {p4hir.dir = #p4hir<dir inout>, p4hir.param_name = "a"}, %arg1: !p4hir.ref<!b8i> {p4hir.dir = #p4hir<dir inout>, p4hir.param_name = "b"},
                           %cond: !p4hir.bool {p4hir.dir = #p4hir<dir in>, p4hir.param_name = "cond"}) {
    %c = p4hir.variable ["c", init] : <!b8i>
    %d = p4hir.variable ["d"] : <!b8i>
    %val = p4hir.read %arg0 : <!b8i>
    p4hir.assign %val, %c : <!b8i>
    %val_0 = p4hir.read %arg1 : <!b8i>
    p4hir.assign %val_0, %c : <!b8i>
    p4hir.if %cond {
      %val_2 = p4hir.read %c : <!b8i>
      p4hir.assign %val_2, %d : <!b8i>
    }
    %val_1 = p4hir.read %c : <!b8i>
    p4hir.assign %val_1, %arg0 : <!b8i>
    p4hir.return
  }
}
