// RUN: p4mlir-translate --typeinference-only %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK: #[[const_int2_b10i:.+]] = #p4hir.int<2> : !b10i
// CHECK: #[[const_int2_i10i:.+]] = #p4hir.int<2> : !i10i
// CHECK: #[[const_int3_b10i:.+]] = #p4hir.int<3> : !b10i
// CHECK: #[[const_int3_i10i:.+]] = #p4hir.int<3> : !i10i

// CHECK-LABEL:   p4hir.func action @bit_add_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_add:.*]] = p4hir.binop(add, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_add]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_add_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs + rhs;
}

// CHECK-LABEL:   p4hir.func action @int_add_int
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_add:.*]] = p4hir.binop(add, %[[val_lhs]], %[[val_rhs]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_add]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_add_int() {
    int<10> lhs;
    int<10> rhs;
    int<10> res = lhs + rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_sub_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_sub:.*]] = p4hir.binop(sub, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_sub]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_sub_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs - rhs;
}

// CHECK-LABEL:   p4hir.func action @int_sub_int
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_sub:.*]] = p4hir.binop(sub, %[[val_lhs]], %[[val_rhs]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_sub]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_sub_int() {
    int<10> lhs;
    int<10> rhs;
    int<10> res = lhs - rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_mul_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_mul:.*]] = p4hir.binop(mul, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_mul]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_mul_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs * rhs;
    res = rhs * rhs;
}

// CHECK-LABEL:   p4hir.func action @int_mul_int
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_mul:.*]] = p4hir.binop(mul, %[[val_lhs]], %[[val_rhs]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_mul]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_mul_int() {
    int<10> lhs;
    int<10> rhs;
    int<10> res = lhs * rhs;
    res = rhs * rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_mul_const_and_const_mul_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[const_int2_b10i:.*]] = p4hir.const #int2_b10i
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_binop_mul_1:.*]] = p4hir.binop(mul, %[[val_lhs]], %[[const_int2_b10i]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_mul_1]], %[[var_res]] : <!b10i>
// CHECK:           %[[const_int3_b10i:.*]] = p4hir.const #int3_b10i
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_mul_2:.*]] = p4hir.binop(mul, %[[const_int3_b10i]], %[[val_rhs]]) : !b10i
// CHECK:           p4hir.assign %[[val_binop_mul_2]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_mul_const_and_const_mul_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs * 2;
    res = 3 * rhs;
}

// CHECK-LABEL:   p4hir.func action @int_mul_const_and_const_mul_int
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[const_int2_i10i:.*]] = p4hir.const #int2_i10i
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i10i>
// CHECK:           %[[val_binop_mul_1:.*]] = p4hir.binop(mul, %[[val_lhs]], %[[const_int2_i10i]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_mul_1]], %[[var_res]] : <!i10i>
// CHECK:           %[[const_int3_i10i:.*]] = p4hir.const #int3_i10i
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_mul_2:.*]] = p4hir.binop(mul, %[[const_int3_i10i]], %[[val_rhs]]) : !i10i
// CHECK:           p4hir.assign %[[val_binop_mul_2]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_mul_const_and_const_mul_int() {
    int<10> lhs;
    int<10> rhs;
    int<10> res = lhs * 2;
    res = 3 * rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_mul_the_same_bit
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_rhs1:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_rhs2:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_mul:.*]] = p4hir.binop(mul, %[[val_rhs1]], %[[val_rhs2]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_mul]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_mul_the_same_bit() {
    bit<10> rhs;
    bit<10> res = rhs * rhs;
}

// CHECK-LABEL:   p4hir.func action @int_mul_the_same_int
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_rhs1:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_rhs2:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_mul:.*]] = p4hir.binop(mul, %[[val_rhs1]], %[[val_rhs2]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_mul]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_mul_the_same_int() {
    int<10> rhs;
    int<10> res = rhs * rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_div_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_div:.*]] = p4hir.binop(div, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_div]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_div_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs / rhs;
}

// action int_div_int() - skipped: div operation is not supported on signed values

// CHECK-LABEL:   p4hir.func action @bit_mod_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_mod:.*]] = p4hir.binop(mod, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_mod]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_mod_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs % rhs;
}

// action int_mod_int() - skipped: mod operation is not supported on signed values

// CHECK-LABEL:   p4hir.func action @bit_sadd_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_sadd:.*]] = p4hir.binop(sadd, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_sadd]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_sadd_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs |+| rhs;
}

// CHECK-LABEL:   p4hir.func action @int_sadd_int
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_sadd:.*]] = p4hir.binop(sadd, %[[val_lhs]], %[[val_rhs]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_sadd]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_sadd_int() {
    int<10> lhs;
    int<10> rhs;
    int<10> res = lhs |+| rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_ssub_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_ssub:.*]] = p4hir.binop(ssub, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_ssub]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_ssub_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs |-| rhs;
}

// CHECK-LABEL:   p4hir.func action @int_ssub_int
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_ssub:.*]] = p4hir.binop(ssub, %[[val_lhs]], %[[val_rhs]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_ssub]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_ssub_int() {
    int<10> lhs;
    int<10> rhs;
    int<10> res = lhs |-| rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_or_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_or:.*]] = p4hir.binop(or, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_or]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_or_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs | rhs;
}

// CHECK-LABEL:   p4hir.func action @int_or_int
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_or:.*]] = p4hir.binop(or, %[[val_lhs]], %[[val_rhs]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_or]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_or_int() {
    int<10> lhs;
    int<10> rhs;
    int<10> res = lhs | rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_and_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_and:.*]] = p4hir.binop(and, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_and]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_and_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs & rhs;
}

// CHECK-LABEL:   p4hir.func action @int_and_int
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_and:.*]] = p4hir.binop(and, %[[val_lhs]], %[[val_rhs]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_and]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_and_int() {
    int<10> lhs;
    int<10> rhs;
    int<10> res = lhs & rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_xor_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_xor:.*]] = p4hir.binop(xor, %[[val_lhs]], %[[val_rhs]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_xor]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit_xor_bit() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs ^ rhs;
}

// CHECK-LABEL:   p4hir.func action @int_xor_int
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i10i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_binop_xor:.*]] = p4hir.binop(xor, %[[val_lhs]], %[[val_rhs]]) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_binop_xor]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int_xor_int() {
    int<10> lhs;
    int<10> rhs;
    int<10> res = lhs ^ rhs;
}

// CHECK-LABEL:   p4hir.func action @complex_sequence
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b10i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[const_int3_b10i:.*]] = p4hir.const #int3_b10i
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_mul_1:.*]] = p4hir.binop(mul, %[[val_rhs]], %[[const_int3_b10i]]) : !b10i
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_lhs]] : <!b10i>
// CHECK:           %[[val_binop_mul_2:.*]] = p4hir.binop(add, %[[val_rhs]], %[[val_binop_mul_1]]) : !b10i
// CHECK:           %[[const_int2_b10i:.*]] = p4hir.const #int2_b10i
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_binop_mul_3:.*]] = p4hir.binop(sub, %[[const_int2_b10i]], %[[val_rhs]]) : !b10i
// CHECK:           %[[val_binop_mul_4:.*]] = p4hir.binop(add, %[[val_binop_mul_2]], %[[val_binop_mul_3]]) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_binop_mul_4]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action complex_sequence() {
    bit<10> lhs;
    bit<10> rhs;
    bit<10> res = lhs + rhs * 3 + (2 - rhs);
}
