// RUN: p4mlir-translate --typeinference-only %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   p4hir.func action @bit5_concat_bit5
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b5i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b5i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b5i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b5i>
// CHECK:           %[[val_concat:.*]] = p4hir.concat(%[[val_lhs]] : !b5i, %[[val_rhs]] : !b5i) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_concat]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit5_concat_bit5() {
    bit<5> lhs;
    bit<5> rhs;
    bit<10> res = lhs ++ rhs;
}

// CHECK-LABEL:   p4hir.func action @bit5_concat_bit10
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b5i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b5i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_concat:.*]] = p4hir.concat(%[[val_lhs]] : !b5i, %[[val_rhs]] : !b10i) : !b15i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["result", init] : <!b15i>
// CHECK:           p4hir.assign %[[val_concat]], %[[var_res]] : <!b15i>
// CHECK:           p4hir.return

action bit5_concat_bit10() {
    bit<5> lhs;
    bit<10> rhs;
    bit<15> result = lhs ++ rhs;
}

// CHECK-LABEL:   p4hir.func action @int5_concat_int5
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i5i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i5i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i5i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i5i>
// CHECK:           %[[val_concat:.*]] = p4hir.concat(%[[val_lhs]] : !i5i, %[[val_rhs]] : !i5i) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["result", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_concat]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int5_concat_int5() {
    int<5> lhs;
    int<5> rhs;
    int<10> result = lhs ++ rhs;
}

// CHECK-LABEL:   p4hir.func action @int5_concat_int10
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i5i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i5i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_concat:.*]] = p4hir.concat(%[[val_lhs]] : !i5i, %[[val_rhs]] : !i10i) : !i15i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["result", init] : <!i15i>
// CHECK:           p4hir.assign %[[val_concat]], %[[var_res]] : <!i15i>
// CHECK:           p4hir.return

action int5_concat_int10() {
    int<5> lhs;
    int<10> rhs;
    int<15> result = lhs ++ rhs;
}

// CHECK-LABEL:   p4hir.func action @bit5_concat_int5
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b5i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i5i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b5i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i5i>
// CHECK:           %[[val_concat:.*]] = p4hir.concat(%[[val_lhs]] : !b5i, %[[val_rhs]] : !i5i) : !b10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["result", init] : <!b10i>
// CHECK:           p4hir.assign %[[val_concat]], %[[var_res]] : <!b10i>
// CHECK:           p4hir.return

action bit5_concat_int5() {
    bit<5> lhs;
    int<5> rhs;
    bit<10> result = lhs ++ rhs;
}

// CHECK-LABEL:   p4hir.func action @bit5_concat_int10
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b5i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!i10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b5i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!i10i>
// CHECK:           %[[val_concat:.*]] = p4hir.concat(%[[val_lhs]] : !b5i, %[[val_rhs]] : !i10i) : !b15i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["result", init] : <!b15i>
// CHECK:           p4hir.assign %[[val_concat]], %[[var_res]] : <!b15i>
// CHECK:           p4hir.return

action bit5_concat_int10() {
    bit<5> lhs;
    int<10> rhs;
    bit<15> result = lhs ++ rhs;
}

// CHECK-LABEL:   p4hir.func action @int5_concat_bit5
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i5i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b5i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i5i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b5i>
// CHECK:           %[[val_concat:.*]] = p4hir.concat(%[[val_lhs]] : !i5i, %[[val_rhs]] : !b5i) : !i10i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["result", init] : <!i10i>
// CHECK:           p4hir.assign %[[val_concat]], %[[var_res]] : <!i10i>
// CHECK:           p4hir.return

action int5_concat_bit5() {
    int<5> lhs;
    bit<5> rhs;
    int<10> result = lhs ++ rhs;
}

// CHECK-LABEL:   p4hir.func action @int5_concat_bit10
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i5i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b10i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i5i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b10i>
// CHECK:           %[[val_concat:.*]] = p4hir.concat(%[[val_lhs]] : !i5i, %[[val_rhs]] : !b10i) : !i15i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["result", init] : <!i15i>
// CHECK:           p4hir.assign %[[val_concat]], %[[var_res]] : <!i15i>
// CHECK:           p4hir.return

action int5_concat_bit10() {
    int<5> lhs;
    bit<10> rhs;
    int<15> result = lhs ++ rhs;
}
