// RUN: p4mlir-translate --typeinference-only %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK: #[[const_int1_infint:.+]] = #p4hir.int<1> : !infint
// CHECK: #[[const_int4_infint:.+]] = #p4hir.int<4> : !infint

// CHECK-LABEL:   p4hir.func action @bit_shl_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b32i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b8i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b32i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b8i>
// CHECK:           %[[val_shlop:.*]] = p4hir.shl(%[[val_lhs]], %[[val_rhs]] : !b8i) : !b32i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b32i>
// CHECK:           p4hir.assign %[[val_shlop]], %[[var_res]] : <!b32i>
// CHECK:           p4hir.return

action bit_shl_bit() {
    bit<32> lhs;
    bit<8> rhs;
    bit<32> res = lhs << rhs;
}

// CHECK-LABEL:   p4hir.func action @int_shl_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i32i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b8i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i32i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b8i>
// CHECK:           %[[val_shlop:.*]] = p4hir.shl(%[[val_lhs]], %[[val_rhs]] : !b8i) : !i32i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i32i>
// CHECK:           p4hir.assign %[[val_shlop]], %[[var_res]] : <!i32i>
// CHECK:           p4hir.return

action int_shl_bit() {
    int<32> lhs;
    bit<8> rhs;
    int<32> res = lhs << rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_shl_const
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b32i>
// CHECK:           %[[const_int1_infint:.*]] = p4hir.const #int1_infint
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b32i>
// CHECK:           %[[val_shlop:.*]] = p4hir.shl(%[[val_lhs]], %[[const_int1_infint]] : !infint) : !b32i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b32i>
// CHECK:           p4hir.assign %[[val_shlop]], %[[var_res]] : <!b32i>
// CHECK:           p4hir.return

action bit_shl_const() {
    bit<32> lhs;
    bit<32> res = lhs << 1;
}

// CHECK-LABEL:   p4hir.func action @int_shl_const
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i32i>
// CHECK:           %[[const_int1_infint:.*]] = p4hir.const #int1_infint
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i32i>
// CHECK:           %[[val_shlop:.*]] = p4hir.shl(%[[val_lhs]], %[[const_int1_infint]] : !infint) : !i32i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i32i>
// CHECK:           p4hir.assign %[[val_shlop]], %[[var_res]] : <!i32i>
// CHECK:           p4hir.return

action int_shl_const() {
    int<32> lhs;
    int<32> res = lhs << 1;
}

// CHECK-LABEL:   p4hir.func action @const_shl_const
// CHECK:           %[[const_res:.*]] = p4hir.const ["res"] #int4_infint
// CHECK:           p4hir.return

action const_shl_const() {
    const int res = 1 << 2;
}

// CHECK-LABEL:   p4hir.func action @bit_shr_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b32i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b8i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b32i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b8i>
// CHECK:           %[[val_shrop:.*]] = p4hir.shr(%[[val_lhs]], %[[val_rhs]] : !b8i) : !b32i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b32i>
// CHECK:           p4hir.assign %[[val_shrop]], %[[var_res]] : <!b32i>
// CHECK:           p4hir.return

action bit_shr_bit() {
    bit<32> lhs;
    bit<8> rhs;
    bit<32> res = lhs >> rhs;
}

// CHECK-LABEL:   p4hir.func action @int_shr_bit
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i32i>
// CHECK:           %[[var_rhs:.*]] = p4hir.variable ["rhs"] : <!b8i>
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i32i>
// CHECK:           %[[val_rhs:.*]] = p4hir.read %[[var_rhs]] : <!b8i>
// CHECK:           %[[val_shrop:.*]] = p4hir.shr(%[[val_lhs]], %[[val_rhs]] : !b8i) : !i32i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i32i>
// CHECK:           p4hir.assign %[[val_shrop]], %[[var_res]] : <!i32i>
// CHECK:           p4hir.return

action int_shr_bit() {
    int<32> lhs;
    bit<8> rhs;
    int<32> res = lhs >> rhs;
}

// CHECK-LABEL:   p4hir.func action @bit_shr_const
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!b32i>
// CHECK:           %[[const_int1_infint:.*]] = p4hir.const #int1_infint
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!b32i>
// CHECK:           %[[val_shrop:.*]] = p4hir.shr(%[[val_lhs]], %[[const_int1_infint]] : !infint) : !b32i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b32i>
// CHECK:           p4hir.assign %[[val_shrop]], %[[var_res]] : <!b32i>
// CHECK:           p4hir.return

action bit_shr_const() {
    bit<32> lhs;
    bit<32> res = lhs >> 1;
}

// CHECK-LABEL:   p4hir.func action @int_shr_const
// CHECK:           %[[var_lhs:.*]] = p4hir.variable ["lhs"] : <!i32i>
// CHECK:           %[[const_int1_infint:.*]] = p4hir.const #int1_infint
// CHECK:           %[[val_lhs:.*]] = p4hir.read %[[var_lhs]] : <!i32i>
// CHECK:           %[[val_shrop:.*]] = p4hir.shr(%[[val_lhs]], %[[const_int1_infint]] : !infint) : !i32i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i32i>
// CHECK:           p4hir.assign %[[val_shrop]], %[[var_res]] : <!i32i>
// CHECK:           p4hir.return

action int_shr_const() {
    int<32> lhs;
    int<32> res = lhs >> 1;
}

// CHECK-LABEL:   p4hir.func action @const_shr_const
// CHECK:           %[[const_res:.*]] = p4hir.const ["res"] #int1_infint
// CHECK:           p4hir.return

action const_shr_const() {
    const int res = 2 >> 1;
}
