// RUN: p4mlir-translate --typeinference-only %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK: #[[const_false:.+]] = #p4hir.bool<false> : !p4hir.bool
// CHECK: #[[const_int_neg1_i8i:.+]] = #p4hir.int<-1> : !i8i
// CHECK: #[[const_int1_i8i:.+]] = #p4hir.int<1> : !i8i

// CHECK-LABEL:   p4hir.func action @plus_bit
// CHECK:           %[[var_a:.*]] = p4hir.variable ["a"] : <!b8i>
// CHECK:           %[[val_a:.*]] = p4hir.read %[[var_a]] : <!b8i>
// CHECK:           %[[val_unary_plus:.*]] = p4hir.unary(plus, %[[val_a]]) : !b8i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b8i>
// CHECK:           p4hir.assign %[[val_unary_plus]], %[[var_res]] : <!b8i>
// CHECK:           p4hir.return

action plus_bit() {
  bit<8> a;
  bit<8> res = +a;
}


// CHECK-LABEL:   p4hir.func action @plus_int
// CHECK:           %[[var_a:.*]] = p4hir.variable ["a"] : <!i8i>
// CHECK:           %[[val_a:.*]] = p4hir.read %[[var_a]] : <!i8i>
// CHECK:           %[[val_unary_plus:.*]] = p4hir.unary(plus, %[[val_a]]) : !i8i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i8i>
// CHECK:           p4hir.assign %[[val_unary_plus]], %[[var_res]] : <!i8i>
// CHECK:           p4hir.return

action plus_int() {
  int<8> a;
  int<8> res = +a;
}

// CHECK-LABEL:   p4hir.func action @plus_const
// CHECK:           %[[const_int1_i8i:.*]] = p4hir.const #int1_i8i
// CHECK:           %[[val_int1_i8i:.*]] = p4hir.cast(%[[const_int1_i8i]] : !i8i) : !i8i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i8i>
// CHECK:           p4hir.assign %[[val_int1_i8i]], %[[var_res]] : <!i8i>
// CHECK:           p4hir.return

action plus_const() {
  int<8> res = +1;
}

// CHECK-LABEL:   p4hir.func action @minus_bit
// CHECK:           %[[var_a:.*]] = p4hir.variable ["a"] : <!b8i>
// CHECK:           %[[val_a:.*]] = p4hir.read %[[var_a]] : <!b8i>
// CHECK:           %[[val_unary_minus:.*]] = p4hir.unary(minus, %[[val_a]]) : !b8i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b8i>
// CHECK:           p4hir.assign %[[val_unary_minus]], %[[var_res]] : <!b8i>
// CHECK:           p4hir.return

action minus_bit() {
  bit<8> a;
  bit<8> res = -a;
}

// CHECK-LABEL:   p4hir.func action @minus_int
// CHECK:           %[[var_a:.*]] = p4hir.variable ["a"] : <!i8i>
// CHECK:           %[[val_a:.*]] = p4hir.read %[[var_a]] : <!i8i>
// CHECK:           %[[val_unary_minus:.*]] = p4hir.unary(minus, %[[val_a]]) : !i8i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i8i>
// CHECK:           p4hir.assign %[[val_unary_minus]], %[[var_res]] : <!i8i>
// CHECK:           p4hir.return

action minus_int() {
  int<8> a;
  int<8> res = -a;
}

// CHECK-LABEL:   p4hir.func action @minus_const
// CHECK:           %[[const_int_neg1_i8i:.*]] = p4hir.const #int-1_i8i
// CHECK:           %[[val_int_neg1_i8i:.*]] = p4hir.cast(%[[const_int_neg1_i8i]] : !i8i) : !i8i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i8i>
// CHECK:           p4hir.assign %[[val_int_neg1_i8i]], %[[var_res]] : <!i8i>
// CHECK:           p4hir.return

action minus_const() {
  int<8> res = -1;
}

// CHECK-LABEL:   p4hir.func action @cmpl_bit
// CHECK:           %[[var_a:.*]] = p4hir.variable ["a"] : <!b8i>
// CHECK:           %[[val_a:.*]] = p4hir.read %[[var_a]] : <!b8i>
// CHECK:           %[[val_unary_cmpl:.*]] = p4hir.unary(cmpl, %[[val_a]]) : !b8i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!b8i>
// CHECK:           p4hir.assign %[[val_unary_cmpl]], %[[var_res]] : <!b8i>
// CHECK:           p4hir.return

action cmpl_bit() {
  bit<8> a;
  bit<8> res = ~a;
}

// CHECK-LABEL:   p4hir.func action @cmpl_int
// CHECK:           %[[var_a:.*]] = p4hir.variable ["a"] : <!i8i>
// CHECK:           %[[val_a:.*]] = p4hir.read %[[var_a]] : <!i8i>
// CHECK:           %[[val_unary_cmpl:.*]] = p4hir.unary(cmpl, %[[val_a]]) : !i8i
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!i8i>
// CHECK:           p4hir.assign %[[val_unary_cmpl]], %[[var_res]] : <!i8i>
// CHECK:           p4hir.return

action cmpl_int() {
  int<8> a;
  int<8> res = ~a;
}

// CHECK-LABEL:   p4hir.func action @not_bool
// CHECK:           %[[var_a:.*]] = p4hir.variable ["a"] : <!p4hir.bool>
// CHECK:           %[[val_a:.*]] = p4hir.read %[[var_a]] : <!p4hir.bool>
// CHECK:           %[[val_unary_not:.*]] = p4hir.unary(not, %[[val_a]]) : !p4hir.bool
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!p4hir.bool>
// CHECK:           p4hir.assign %[[val_unary_not]], %[[var_res]] : <!p4hir.bool>
// CHECK:           p4hir.return

action not_bool() {
  bool a;
  bool res = !a;
}

// CHECK-LABEL:   p4hir.func action @not_const
// CHECK:           %[[const_false:.*]] = p4hir.const #false
// CHECK:           %[[var_res:.*]] = p4hir.variable ["res", init] : <!p4hir.bool>
// CHECK:           p4hir.assign %[[const_false]], %[[var_res]] : <!p4hir.bool>
// CHECK:           p4hir.return

action not_const() {
  bool res = !true;
}
