// SPDX-FileCopyrightText: 2026 The P4 Language Consortium
//
// SPDX-License-Identifier: Apache-2.0

// RUN: p4mlir-opt --pass-pipeline='builtin.module(any(sroa))' < %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

!validity_bit = !p4hir.validity.bit
!i32i = !p4hir.int<32>
!b32i = !p4hir.bit<32>
!b9i = !p4hir.bit<9>
!T = !p4hir.struct<"T", t1: !i32i, t2: !b32i, t3: !b9i>
!S = !p4hir.struct<"S", t: !T, s1 : !b9i>
!C = !p4hir.array<2 x !i32i>
#int1_i32i = #p4hir.int<1> : !i32i
#int2_i32i = #p4hir.int<2> : !i32i
#int3_b9i = #p4hir.int<3> : !b9i
!H = !p4hir.header<"T", t1: !i32i, t2: !b32i, t3: !b9i, __valid: !validity_bit>
#valid = #p4hir<validity.bit valid> : !validity_bit

module {
// CHECK: #[[$ATTR_0:.+]] = #p4hir.int<0> : !b32i
// CHECK: #[[$ATTR_1:.+]] = #p4hir.int<1> : !b32i
// CHECK: #[[$ATTR_2:.+]] = #p4hir.int<1> : !i32i
// CHECK-LABEL:   p4hir.func @struct_sroa(
// CHECK-SAME:      %[[ARG0:.*]]: !i32i,
// CHECK-SAME:      %[[ARG1:.*]]: !b32i,
// CHECK-SAME:      %[[ARG2:.*]]: !b9i) -> !b9i {
// CHECK:           %[[VAL_0:.*]] = p4hir.variable ["t.field0", init] : <!i32i>
// CHECK:           %[[VAL_1:.*]] = p4hir.variable ["t.field1", init] : <!b32i>
// CHECK:           %[[VAL_2:.*]] = p4hir.variable ["t.field2", init] : <!b9i>
// CHECK:           %[[VAL_3:.*]] = p4hir.struct (%[[ARG0]], %[[ARG1]], %[[ARG2]]) : !T
// CHECK:           %[[VAL_4:.*]] = p4hir.struct_extract %[[VAL_3]]["t1"] : !T
// CHECK:           p4hir.assign %[[VAL_4]], %[[VAL_0]] : <!i32i>
// CHECK:           %[[VAL_5:.*]] = p4hir.struct_extract %[[VAL_3]]["t2"] : !T
// CHECK:           p4hir.assign %[[VAL_5]], %[[VAL_1]] : <!b32i>
// CHECK:           %[[VAL_6:.*]] = p4hir.struct_extract %[[VAL_3]]["t3"] : !T
// CHECK:           p4hir.assign %[[VAL_6]], %[[VAL_2]] : <!b9i>
// CHECK:           %[[VAL_7:.*]] = p4hir.read %[[VAL_0]] : <!i32i>
// CHECK:           %[[VAL_8:.*]] = p4hir.read %[[VAL_1]] : <!b32i>
// CHECK:           %[[VAL_9:.*]] = p4hir.read %[[VAL_2]] : <!b9i>
// CHECK:           %[[VAL_10:.*]] = p4hir.struct (%[[VAL_7]], %[[VAL_8]], %[[VAL_9]]) : !T
// CHECK:           %[[VAL_11:.*]] = p4hir.variable ["S.field0.field0", init] : <!i32i>
// CHECK:           %[[VAL_12:.*]] = p4hir.variable ["S.field0.field1", init] : <!b32i>
// CHECK:           %[[VAL_13:.*]] = p4hir.variable ["S.field0.field2", init] : <!b9i>
// CHECK:           %[[VAL_14:.*]] = p4hir.variable ["S.field1", init] : <!b9i>
// CHECK:           %[[VAL_15:.*]] = p4hir.struct_extract %[[VAL_10]]["t1"] : !T
// CHECK:           p4hir.assign %[[VAL_15]], %[[VAL_11]] : <!i32i>
// CHECK:           %[[VAL_16:.*]] = p4hir.struct_extract %[[VAL_10]]["t2"] : !T
// CHECK:           p4hir.assign %[[VAL_16]], %[[VAL_12]] : <!b32i>
// CHECK:           %[[VAL_17:.*]] = p4hir.struct_extract %[[VAL_10]]["t3"] : !T
// CHECK:           p4hir.assign %[[VAL_17]], %[[VAL_13]] : <!b9i>
// CHECK:           %[[VAL_18:.*]] = p4hir.read %[[VAL_11]] : <!i32i>
// CHECK:           %[[VAL_19:.*]] = p4hir.read %[[VAL_12]] : <!b32i>
// CHECK:           %[[VAL_20:.*]] = p4hir.read %[[VAL_13]] : <!b9i>
// CHECK:           %[[VAL_21:.*]] = p4hir.struct (%[[VAL_18]], %[[VAL_19]], %[[VAL_20]]) : !T
// CHECK:           %[[VAL_22:.*]] = p4hir.read %[[VAL_14]] : <!b9i>
// CHECK:           %[[VAL_23:.*]] = p4hir.struct (%[[VAL_21]], %[[VAL_22]]) : !S
// CHECK:           %[[VAL_24:.*]] = p4hir.read %[[VAL_13]] : <!b9i>
// CHECK:           p4hir.return %[[VAL_24]] : !b9i
// CHECK:         }
  p4hir.func @struct_sroa(%arg0 : !i32i, %arg1 : !b32i, %arg2 : !b9i) -> !b9i {
    %t = p4hir.variable ["t", init] : <!T>
    %t_val = p4hir.struct (%arg0, %arg1, %arg2) : !T
    p4hir.assign %t_val, %t : <!T>
    %t_val2 = p4hir.read %t : <!T>
    %s = p4hir.variable ["S", init] : <!S>
    %t_field_ref = p4hir.struct_field_ref %s ["t"] : <!S>
    p4hir.assign %t_val2, %t_field_ref : <!T>
    %s_val = p4hir.read %s : <!S>
    %t3_field_ref2 = p4hir.struct_field_ref %t_field_ref ["t3"] : <!T>
    %t3_val = p4hir.read %t3_field_ref2 : <!b9i>
    p4hir.return %t3_val : !b9i
  }
// CHECK-LABEL:   p4hir.func @array_sroa(
// CHECK-SAME:      %[[ARG0:.*]]: !i32i,
// CHECK-SAME:      %[[ARG1:.*]]: !i32i) -> !i32i {
// CHECK:           %[[VAL_0:.*]] = p4hir.variable ["c.field0", init] : <!i32i>
// CHECK:           %[[VAL_1:.*]] = p4hir.variable ["c.field1", init] : <!i32i>
// CHECK:           %[[VAL_2:.*]] = p4hir.array {{\[}}%[[ARG0]], %[[ARG1]]] : !arr_2xi32i
// CHECK:           %[[VAL_3:.*]] = p4hir.const #[[$ATTR_0]]
// CHECK:           %[[VAL_4:.*]] = p4hir.array_get %[[VAL_2]]{{\[}}%[[VAL_3]]] : !arr_2xi32i, !b32i
// CHECK:           p4hir.assign %[[VAL_4]], %[[VAL_0]] : <!i32i>
// CHECK:           %[[VAL_5:.*]] = p4hir.const #[[$ATTR_1]]
// CHECK:           %[[VAL_6:.*]] = p4hir.array_get %[[VAL_2]]{{\[}}%[[VAL_5]]] : !arr_2xi32i, !b32i
// CHECK:           p4hir.assign %[[VAL_6]], %[[VAL_1]] : <!i32i>
// CHECK:           %[[VAL_7:.*]] = p4hir.read %[[VAL_0]] : <!i32i>
// CHECK:           %[[VAL_8:.*]] = p4hir.read %[[VAL_1]] : <!i32i>
// CHECK:           %[[VAL_9:.*]] = p4hir.array {{\[}}%[[VAL_7]], %[[VAL_8]]] : !arr_2xi32i
// CHECK:           %[[VAL_10:.*]] = p4hir.const #[[$ATTR_2]]
// CHECK:           p4hir.assign %[[VAL_10]], %[[VAL_1]] : <!i32i>
// CHECK:           %[[VAL_11:.*]] = p4hir.read %[[VAL_1]] : <!i32i>
// CHECK:           p4hir.return %[[VAL_11]] : !i32i
// CHECK:         }
  p4hir.func @array_sroa(%arg0 : !i32i, %arg1 : !i32i) -> !i32i {
    %c = p4hir.variable ["c", init] : <!C>
    %c_val = p4hir.array [%arg0, %arg1] : !C
    p4hir.assign %c_val, %c : <!C>
    %t_val2 = p4hir.read %c : <!C>
    %idx = p4hir.const #p4hir.int<1> : !i32i
    %aa_ref = p4hir.array_element_ref %c[%idx] : !p4hir.ref<!C>, !i32i
    p4hir.assign %idx, %aa_ref : <!i32i>
    %c_val2 = p4hir.read %aa_ref : <!i32i>
    p4hir.return %c_val2 : !i32i
  }

  p4hir.func @hdr_sroa(%arg0 : !i32i, %arg1 : !b32i, %arg2 : !b9i) -> !b9i {
    %h = p4hir.variable ["h", init] : <!H>
    %valid = p4hir.const #valid
    %h_val = p4hir.struct (%arg0, %arg1, %arg2, %valid) : !H
    p4hir.assign %h_val, %h : <!H>
    %h_val2 = p4hir.read %h : <!H>
    %t3_field_ref2 = p4hir.struct_field_ref %h ["t3"] : <!H>
    %t3_val = p4hir.read %t3_field_ref2 : <!b9i>
    p4hir.return %t3_val : !b9i
  }
}
